name: Docker Compose Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.SERVER_HOST }}
        #username: ${{ secrets.SERVER_USERNAME }}
        #key: ${{ secrets.SERVER_PRIVATE_KEY }}
        #script: |
        #  cd /path/to/project
        #  docker-compose pull
        #  docker-compose up -d
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home/platform
          git pull origin master
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d
