name: Docker Compose Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#    - name: Log in to Docker Hub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#
#    - name: Build and push Docker images
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: ./docker-compose.prod.yml
#        push: true
#        tags: latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.SERVER_HOST }}
        #username: ${{ secrets.SERVER_USERNAME }}
        #key: ${{ secrets.SERVER_PRIVATE_KEY }}
        #script: |
        #  cd /path/to/project
        #  docker-compose pull
        #  docker-compose up -d
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          #set -a
           ./envs/test.env
          cd /home
          #gh repo clone itmo0project0management/platform
          cd platform/
          git pull
          #git pull master
          #docker compose -f docker-compose.test.yml pull
          #docker compose -f docker-compose.test.yml down
          #docker compose -f docker-compose.test.yml up -d
          #docker compose --env-file envs/prod.env up
          docker compose restart odoo16
