name: Docker Compose Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          #set -a
          
          cd /home
          #gh repo clone itmo0project0management/platform
          cd platform/
          git pull
          #git pull master
          ./envs/test.env
          docker-compose -f docker-compose.test.yml pull
          docker-compose -f docker-compose.test.yml down
          docker-compose -f docker-compose.test.yml up -d
          #docker compose --env-file envs/test.env up
          #docker compose restart odoo16
